{
 "title": "Host Resource Usage",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"prometheus\",instance=\"13.73.153.234:9100\",mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\"} - node_memory_MemFree_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\"} - node_memory_Cached_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\"} - node_memory_Buffers_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\"}",
     "legendFormat": "Cached"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"prometheus\",instance=\"13.73.153.234:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"prometheus\",instance=\"13.73.153.234:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs|nsfs\",device!~\"gvfsd_fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\",device!~\"/dev/loop.*\", device!~\"tmpfs|nsfs\", device!=\"gvfsd-fuse\"} -\nnode_filesystem_avail_bytes{job=\"prometheus\",instance=\"13.73.153.234:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}